@base_url = http://localhost:8000
@token = 2|6rFDqsElEaj3FDtUrBjFW6CoHAqyFpGGZIVMZQqdacf90e5b

### Category GET ALL
GET {{base_url}}/api/category/
Authorization: Bearer {{token}}

### Get By Id
GET {{base_url}}/api/category/1
Authorization: Bearer {{token}}

### Get By Similar Query
GET {{base_url}}/api/category?q=s
Authorization: Bearer {{token}}

### Create
POST {{base_url}}/api/category/
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nama": "Desserts"
}

### Update
PUT {{base_url}}/api/category/2
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nama": "Mie"
}

### Delete
DELETE {{base_url}}/api/category/10
Authorization: Bearer {{token}}
Content-Type: application/json
