@base_url = http://indo.prinafsika.world:8000
@token = 1|xODJuvOdR7Dh5zKTp6gqU3LmfLiE7xW8eAR1Awc43310e786

### Food
GET {{base_url}}/api/food/
Authorization: Bearer {{token}}

### Food By Id
GET {{base_url}}/api/food/20
Authorization: Bearer {{token}}

### Add New Food (POST request)
POST {{base_url}}/api/food/
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nama": "Pizza Margheritas",
    "harga": 150000,
    "variant": "Balado Jagung",
    "kategori_id": 1,
    "gambar": "url_gambar_pizza.jpg",
    "size_ids": [1, 2, 3],
    "tersedia": 1
}

### Update Food (PUT request)
PUT {{base_url}}/api/food/19
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nama": "Ramen",
    "harga": 15000,
    "variant": "Pedas",
    "kategori_id": 2,
    "size_ids": [1],
    "tersedia": 1
}

### Delete Food (DELETE request)
DELETE {{base_url}}/api/food/1
Authorization: Bearer {{token}}
