@base_url = http://localhost:8000
@token = 2|6rFDqsElEaj3FDtUrBjFW6CoHAqyFpGGZIVMZQqdacf90e5b

### size GET ALL
GET {{base_url}}/api/size/
Authorization: Bearer {{token}}

### Get By Id
GET {{base_url}}/api/size/5
Authorization: Bearer {{token}}

### Create
POST {{base_url}}/api/size/
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nama": "Smallss"
}

### Update
PUT {{base_url}}/api/size/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nama": "Large Banget"
}

### Delete
DELETE {{base_url}}/api/size/4
Authorization: Bearer {{token}}
Content-Type: application/json
