@base_url = http://localhost:8000
@token = 4|TwrAOpXNTQgQzuSwjEtKOeeunKrJ9uw53Q90HgbY9acc0fce

### size GET ALL
GET {{base_url}}/api/size/
Authorization: Bearer {{token}}

### Get By Id
GET {{base_url}}:8000/api/size/1
Authorization: Bearer {{token}}

### Create
POST {{base_url}}:8000/api/size/
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nama": "Samyangz"
}

### Update
PUT {{base_url}}:8000/api/size/8
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nama": "Sayang"
}

### Delete
DELETE {{base_url}}:8000/api/size/4
Authorization: Bearer {{token}}
Content-Type: application/json
