@base_url = http://indo.prinafsika.world:8000
@token = 2|IsUljdKJU6kIs4ZLpMQmRlkSiYcoXpfxkSxOv77j8c71ae27

###
GET {{base_url}}/api/user/
Authorization: Bearer {{token}}

###
POST {{base_url}}/api/register/
Content-Type: application/json

{
    "name": "adminz",
    "email": "adminz@mail.com",
    "password": "admin1234",
    "password_confirmation": "admin1234"
}

### LOGIN
POST {{base_url}}/api/login
Content-Type: application/json

{
    "email": "adminz@mail.com",
    "password": "admin1234"
}

### REGISTER
POST {{base_url}}/api/register
Content-Type: application/json

{
    "name": "Prinafsika",
    "email": "prinafsika@mail.com",
    "password": "admin1234",
    "password_confirmation": "admin1234"
}

### LOGOUT
POST {{base_url}}/api/logout
Accept: application/json
Authorization: Bearer {{token}}
